use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR missing");
    let out_path = Path::new(&out_dir).join("init_elf.rs");

    let init_path = env::var("MANTRA_INIT_ELF").ok();
    let bytes = init_path
        .as_deref()
        .and_then(|p| fs::read(p).ok())
        .unwrap_or_default();

    // Make rebuilds deterministic when the init ELF changes.
    if let Some(p) = init_path.as_deref() {
        println!("cargo:rerun-if-changed={}", p);
    }

    let mut s = String::new();
    s.push_str("// @generated by build.rs\n");
    s.push_str("pub static INIT_ELF: &[u8] = &[\n");
    for chunk in bytes.chunks(12) {
        s.push_str("    ");
        for b in chunk {
            s.push_str(&format!("0x{:02x},", b));
        }
        s.push('\n');
    }
    s.push_str("];\n");

    fs::write(out_path, s).expect("write init_elf.rs");
}

